server:
  port: 9004
  servlet:
    context-path: /

spring:
  application:
    name: offcnpe_mobile
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  redis:
    host: 10.10.33.192
    port: 6379
    password: 123456

dubbo:
  scan:
    base-packages: com.xie.mobile.controller
  registry:
    address: zookeeper://10.10.33.192:2181
    timeout: 1000000
fileUploadPath: E:\LdeaDom1\xiazai