server:
  port: 9003
  servlet:
    context-path: /

spring:
  application:
    name: offcnxie_controler
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  redis:
    host: 10.10.33.110
    port: 6379
    password: 123456

dubbo:
  scan:
    base-packages: com.xie.controller,com.xie.service
  registry:
    address: zookeeper://10.10.33.110:2181
    timeout: 1000000
fileUploadPath: E:\LdeaDom1\xiazai